### ISSUE TITLE
`getObject()` for Yup reports types of DefinitelyTyped

### ISSUE THREAD

**Issue by karlhorky** [algolia/npm-search#1089]
Hi @Haroenv and other maintainers 👋 Hope you are well! Thanks again for your continued effort on the projects in the Algolia ecosystem!

I'm not sure if I'm reporting this in the right place, but I wanted to reach out about what appears to be a data problem with `npm-search` index (we've only seen a single library so far):

Running `index.getObject()` with the package name [`yup`](https://www.npmjs.com/package/yup) returns the following:

```js
{
  types: {
    ts: 'definitely-typed',
    definitelyTyped: '@types/yup',
  },
}
```

However, on the npm website, [the `yup` package](https://www.npmjs.com/package/yup) is reported as having built-in types and [the `@types/yup` package](https://www.npmjs.com/package/@types/yup) has been deprecated:

<img width="364" alt="Screenshot 2022-12-05 at 19 58 19" src="https://user-images.githubusercontent.com/1935696/205720370-7f1ab291-c5c9-4978-b0d3-b39a76cbc0f3.png">

<img width="483" alt="Screenshot 2022-12-05 at 19 59 46" src="https://user-images.githubusercontent.com/1935696/205720616-4f12161f-f5a0-4880-9fd0-5f2866428801.png">

Both the current version and the beta version of `yup` have no `"types"` or `"typings"` keys in the `package.json`:

- https://unpkg.com/browse/yup@0.32.11/package.json
- https://unpkg.com/browse/yup@1.0.0-beta.8/package.json

For the current `yup@0.32.11`, there is however no `index.d.ts` in the root:

- https://unpkg.com/browse/yup@0.32.11/index.d.ts (404)

But there is one in `yup@1.0.0-beta.8`:

- https://unpkg.com/browse/yup@1.0.0-beta.8/index.d.ts

Is the npm website or Algolia's index wrong? (seems like npm website is wrong 🤔)

---

Our usage:

```ts
const client = algoliasearch(
  'XXX',
  'xxxxxxxxxxx',
);

const index = client.initIndex('npm-search');

const results = await index.getObject<AlgoliaObj>(dependency, {
  attributesToRetrieve: ['types'],
});

const definitelyTypedPackageName = results.types?.definitelyTyped;
```

https://github.com/upleveled/preflight/blob/5af8a398ec370c79e22ab770307ec81d574c8e29/src/checks/noDependencyProblems/noDependenciesWithoutTypes.ts#L63-L67

**Comment by Haroenv** [comment]
I think the logic for deciding what's typed is wrong in the algolia index. npm correctly detects that there's .d.ts inside the `es` folder, but we don't. 

I can see two possible improvements here:

1. make sure to exclude deprecated definitely-typed packages (does that count as builtin or no typescript support? usually it happens when the package adds their own TS definitions, but it could also be deprecated completely)
2. improve the check in this project which reads the file names so it also detects yup as having typescript support (if it's correct of course) (this file exists: https://unpkg.com/browse/yup@0.32.11/es/index.d.ts)

**Comment by karlhorky** [comment]
Oh, another problem, looks like Microsoft deleted the "create a search index" function in June: 

https://github.com/microsoft/DefinitelyTyped-tools/pull/456#issuecomment-1339035665

Maybe a new method is needed for determining this information:

https://github.com/algolia/npm-search/blob/d99c31fbe733953d39e498f9c7d982b2e09f3458/src/typescript/index.ts#L24-L40

**Comment by karlhorky** [comment]
Ok added a new issue for this, since it's a bit unrelated: https://github.com/algolia/npm-search/issues/1090

**Comment by karlhorky** [comment]
> I can see two possible improvements here:
> 
> 1. make sure to exclude deprecated definitely-typed packages (does that count as builtin or no typescript support? usually it happens when the package adds their own TS definitions, but it could also be deprecated completely)
> 2. improve the check in this project which reads the file names so it also detects yup as having typescript support (if it's correct of course) (this file exists: [unpkg.com/browse/yup@0.32.11/es/index.d.ts](https://unpkg.com/browse/yup@0.32.11/es/index.d.ts))
> 
> Are you interested in investigating those?

I think @Josehower would take over 2. above, I'll let him continue here.

**Comment by Josehower** [comment]
Hi @Haroenv thanks for your time,

I have been trying to setup the project on my machine so try to research a bit more about the problem or potential solutions to it, but I can't make the app to run locally is asking me a API key, i tried with the API key we use on one of our services but it didn't work.

```
➜  npm-search git:(master) apiKey=xxxxxxxxxxxxxxxxx yarn dev  
Dec 6 14:50:09 :moyai: npm :left_right_arrow: Algolia replication starts ⛷ :snail: 🛰 { version: '1.7.13' }
Dec 6
    message: 'Method not allowe 14:50:09 :muscle:  Setting up Algolia OFCNCOG2CU [ 'npm-search-bootstrap', 'npm-search' ]
Dec 6 14:50:09 ⛑   API started on port 8000
Dec 6 14:50:10 {
  err: {
    name: 'ApiError',
    message: 'Method not allowed with this API key',
    status: 403,
    transporterStackTrace: [ [Object] ]
  }
}
  err: Error: Error during run
      at ./dist/src/index.js:99:23
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
Dec 6 14:50:10 Close was requested
Dec 6 14:50:10 Stopped Main gracefully

```
Wondering how can I get that API key to make it work of if there is an specific setup that need to be done, unfortunately I couldn't find the setup on the README.md

**Comment by Haroenv** [comment]
DM me on Twitter, I can set you up with a testing account  for this :) it needs large limits

**Comment by Haroenv** [comment]
The order was chosen for performance, as DT doesn't require any extra network requests. Maybe if it's deprecated we still fall through to "included" checks, but regularly we keep DT first?

**Comment by jablko** [comment]
I'm not familiar with how Algolia npm-search works, I'm kinda surprised `yup` falls through the first case: https://github.com/algolia/npm-search/blob/d99c31fbe733953d39e498f9c7d982b2e09f3458/src/typescript/index.ts#L64-L67

Are `GetPackage` and `NicePackage` not the npm registry metadata, which contains `"types": "./index.d.ts"` for `yup`? https://registry.npmjs.org/yup https://github.com/algolia/npm-search/blob/d99c31fbe733953d39e498f9c7d982b2e09f3458/src/formatPkg.ts#L64-L67 https://github.com/algolia/npm-search/blob/d99c31fbe733953d39e498f9c7d982b2e09f3458/src/formatPkg.ts#L134

**Comment by karlhorky** [comment]
Maybe it's taking the current version `yup@0.32.11` which does not have `"types": "index.d.ts"`:

https://unpkg.com/browse/yup@0.32.11/package.json

**Comment by Josehower** [comment]
I already tested the solution from @jablko and it seems to work fine

https://github.com/algolia/npm-search/issues/1089#issuecomment-1339544822

![image](https://user-images.githubusercontent.com/61600906/205976850-2472373f-74d0-4ca1-a297-a317db9a0b9e.png)

if @Haroenv approves I can create the PR in no time

**Comment by Josehower** [comment]
I have created a PR that applies fix from @jablko 

https://github.com/algolia/npm-search/pull/1091

good energy 👍👍👍👍

**Comment by karlhorky** [comment]
@Josehower @Haroenv Thanks for creating and merging #1091 🙌 

I think this hasn't taken into account the second improvement that @Haroenv [mentioned above](https://github.com/algolia/npm-search/issues/1089#issuecomment-1339032295) though:

> 1. make sure to exclude deprecated definitely-typed packages (does that count as builtin or no typescript support? usually it happens when the package adds their own TS definitions, but it could also be deprecated completely)

@Haroenv can you reopen this? Or should I create a new issue for this improvement?

**Comment by Haroenv** [comment]
I think with the changed order, the point 1 no longer is needed, unless you see some cases where that would still be relevant?
