### ISSUE TITLE
4+ days indexing delay

### ISSUE THREAD

**Issue by MartinKolarik** [algolia/npm-search#1112]
Based on #1110, #1111, and https://github.com/jsdelivr/www.jsdelivr.com/issues/518 it seems there's currently more than 4 days of delay in the indexing process.

**Comment by hoijnet** [comment]
Looks like I have the same issues, currently 10 days and counting for this package now: [`@dfrnt/gatsby-source-graphql-nodes](https://www.npmjs.com/package/@dfrnt/gatsby-source-graphql-nodes), also another package that I know people have started using successfully in Gatsby that is also not added yet [gatsby-mdx-remote](https://www.npmjs.com/package/gatsby-mdx-remote).

**Comment by hoijnet** [comment]
Still no update?

**Comment by Haroenv** [comment]
Sorry, there's not much we can do to make this faster, the processing is quite complex and easily gets overloaded.

**Comment by hoijnet** [comment]
I take it an update is on its way, but it has been indexing for about two weeks now? Fingers crossed it completes soon ☀️

**Comment by Chaitanya-Raj** [comment]
The same issue is occurring with https://www.jsdelivr.com/package/npm/@teamepyc/sliders. Loading the files from the [CDN](https://cdn.jsdelivr.net/npm/@teamepyc/sliders/) works but it doesn't show up in the search.

**Comment by zachmerrill** [comment]
My company's NPM package version in search hasn't indexed since March 21st. 

@Haroenv any update on this? The [CI failed 4 months ago](https://app.circleci.com/pipelines/github/algolia/npm-search?branch=master) and your [Datadog shows no data](https://p.datadoghq.com/sb/2b51baa8-c54a-11eb-a5a4-da7ad0900002-4973ed88f5be0d93c350fcb0ea2e7f0c?from_ts=1685116426250&to_ts=1685721226250&live=true). Is the indexing up and running?

**Comment by arcanis** [comment]
The problem likely comes from npm, but no progress on their side yet: https://github.com/npm/feedback/discussions/937 😕

**Comment by Eprince-hub** [comment]
I am also having some issues with the indexing, as it seems that the [@apollo/experimental-nextjs-app-support](https://www.npmjs.com/package/@apollo/experimental-nextjs-app-support?activeTab=versions) package has not been indexed since it was released a few months ago on npm.

**Comment by arcanis** [comment]
It seems some of the missing packages have been synced to replicate.npmjs.org, but they are still missing from the Algolia search. For instance Vite is still referencing 4.2 as the last version, and patch-package as 6.x.

**Comment by MartinKolarik** [comment]
We're working together with Algolia to improve the sync process. Will post when I know more about the current status.

**Comment by quinton-ashley** [comment]
How have you guys not fixed an issue of this magnitude that's been known about since April? It's been 4 months.

**Comment by vishwas-r** [comment]
The issue is same with https://www.jsdelivr.com/package/npm/@canvasjs/charts package also! It's been more than 3 months since the package was published, but not getting indexed & shown in the search result yet!

**Comment by jasongodev** [comment]
I just encountered this nonsense and I guarantee a PostgreSQL implementation of indexing jsdelivr and npm will be much faster in updating. Basic full text search will work decently in npm's search context where keywords and a description forms the basic search context.

Why are we using Algolia aside from "hey it's Algolia, failure resilient search, shiny object cool gizmo because it's Algolia, sounds regal"

Maybe it's time to reevaluate and rethink the search feature and indexing for npm packages.

**Comment by quinton-ashley** [comment]
@jasongodev Don't worry I made a PR #1139 that fixes the issue. :)

**Comment by MartinKolarik** [comment]
@jasongodev the current state of this project is a result of multiple problems combined but none of them is related to the actual search engine. A PostgreSQL or any other implementation would have the same problems. 

That said, we (jsDelivr) had a productive call with the Algolia team last week and I think all current issues can be resolved during the next month.

**Comment by quinton-ashley** [comment]
that's great news

**Comment by MartinKolarik** [comment]
We're now running a fresh bootstrap with many improvements (#1140). It'll take about a week to reindex everything and if it's all good after that, the new index will likely replace the current one.

**Comment by MartinKolarik** [comment]
As discussed in #1140, we expect all changes (and all up-to-date data) to be live tomorrow.

**Comment by hoijnet** [comment]
Fantastic! Finally a solution in sight! Looking forward tonseeing the results of your work!!!

**Comment by karlhorky** [comment]
Thanks so much @MartinKolarik and reviewers @pixelastic and @bodinsamuel for the considerable effort in #1140 🙌 

This is going to affect a lot of downstream users!

**Comment by termosa** [comment]
@MartinKolarik I was following this thread hoping that it will fix an issue for me.

But **CodeSandbox** still doesn't show the [use-request](https://www.npmjs.com/package/use-request) even if the whole name is written in the search.
I have been talking with their support and they have said that they cannot do anything as it is on side of Algolia.

Any hope that it can be resolved somehow?
Thank you in advance!

**Comment by MartinKolarik** [comment]
@termosa if you check [here](https://www.jsdelivr.com/?query=use-request) the module is listed (in the 6th place) so it is present in the Algolia data.

**Comment by termosa** [comment]
Terrific. I surmise that the ranking does not depend solely on the name. Therefore, even if a query exactly matches the name, it doesn't necessarily guarantee that it will be the first one.
Alright, I can proceed from here.
Thank you very much, @MartinKolarik!
