### ISSUE TITLE
Intermittent npm failing test because of jest timeout

### ISSUE THREAD

**Issue by pixelastic** [algolia/npm-search#1144]
Running `yarn test` sometimes fails (both locally as a pre-commit hook, and [even on the CI](https://github.com/algolia/npm-search/actions/runs/6589742828/job/17904869663#step:7:29)) with the following error:

```
FAIL src/npm/__tests__/index.test.ts (26.801 s)
  ● findAll() › contains the correct keys

    thrown: "Exceeded timeout of 15000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

       7 |
       8 | describe('findAll()', () => {
    >  9 |   it('contains the correct keys', async () => {
         |   ^
      10 |     const all = await api.findAll({ limit: 2, startkey: '0' });
      11 |
      12 |     expect(all).toEqual(

      at src/npm/__tests__/index.test.ts:9:3
      at Object.<anonymous> (src/npm/__tests__/index.test.ts:8:1)
```

@Haroenv @MartinKolarik any idea on how to mitigate this?

**Comment by MartinKolarik** [comment]
I believe the tests sometimes call real remote APIs, which is obviously not great. These calls should be mocked via https://github.com/nock/nock

**Comment by Haroenv** [comment]
There is an advantage to actually testing the real api (so ci fails if they accidentally change the api, which obviously has happened). Best would be to do:

1. use nock or another mock so the tests don't actually do requests
2. periodically, run the tests without mock as well, and make sure we get notified when it fails (this test can have a higher timeout)

**Comment by pixelastic** [comment]
I like the idea of keeping it real and having some pro-active way of check if the external endpoints we query have changed.

@Haroenv how do you suggest we handle the "periodically" part? Would it be a local script we sometimes manually run? A specific test that is "randomly" triggered every (some kind of sampling)? Or a CRON job that periodically do a sanity check?

I think the CRON job coupled with a notification system (creating an issue) might be the best way

**Comment by MartinKolarik** [comment]
> I think the CRON job coupled with a notification system (creating an issue) might be the best way

GH actions can run on schedule, and they notify the author in case of a failure. Either way, if the goal is to verify the real structure, we should have a couple of retries + larger timeout because, as we know very well, the API fails rather often. Then, it should be fine either as a cron job or even as it is.

**Comment by pixelastic** [comment]
FYI I started the work in https://github.com/algolia/npm-search/pull/1154

Failing tests moved in their own `api-control` folder, and run everyday on CI. We could probably add more retries and timeouts, but for now it moves it out of my own to continue the CI fixes :)

> GH actions can run on schedule, and they notify the author in case of a failure.
Who would be the author notified in case of scheduled GitHub actions?
