### ISSUE TITLE
Consider changing "exactOnSingleWordQuery" to "word"

### ISSUE THREAD

**Issue by MartinKolarik** [algolia/npm-search#1226]
This is something I'd like to look into after #1190. Some scoped packages rank badly because of the `exactOnSingleWordQuery: attribute` setting.

E.g., for the query `angular`, the best result is `@angular/core`, but this is considered a partial match because only one of the two words in the attribute matched. Then, there are several packages that include `angular` as a keyword and, therefore, have an "exact" match on the attribute and rank higher, leaving the correct package in the 8th place.

A solution *might* be changing `exactOnSingleWordQuery` to `word` as a full word match in the title should certainly have a higher priority than it has now. The change shouldn't affect `keywords` much, and as for `description`, we could probably exclude it from the exact criterion entirely (which would basically mean no change compared to now, as the full description text is hardly going to match any reasonable query).

**Comment by Haroenv** [comment]
Great idea, seems like that will aid in matching indeed.

**Comment by MartinKolarik** [comment]
Also improves things like `vue-router`.
