### ISSUE TITLE
Don't crash replication when npm crashes

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#124]
We have one crash per day, let's investigate it

**Comment by vvo** [comment]
{ [unknown_error: Database encountered an unknown error]
  status: 503,
  name: 'unknown_error',
  message: 'Database encountered an unknown error',
  error: true,
  data: '<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n\n' }

**Comment by Haroenv** [comment]
same as #382, but that issue has more actionable comments
