### ISSUE TITLE
Package not found after months of being published

### ISSUE THREAD

**Issue by alirezamirian** [algolia/npm-search#1314]
[@danske/sapphire-react](https://www.npmjs.com/package/@danske/sapphire-react) package is not found (making it not possible to use it in codesandbox), but it does on npm search: https://www.npmjs.com/search?q=%40danske%2Fsapphire-react

**Comment by Haroenv** [comment]
Do you see any pattern in missing packages or just this one?

**Comment by alirezamirian** [comment]
This one seems to be the only one in missing in @danske scope.

**Comment by MartinKolarik** [comment]
Hey, I'm not sure what happened here but right now I can see the package in the results: https://www.jsdelivr.com/?query=%40danske%2Fsapphire-react
