### ISSUE TITLE
How to filter out deprecated packages?

### ISSUE THREAD

**Issue by KyleAMathews** [algolia/npm-search#159]
I already have one `<RefinementList>` for specifying Gatsby's keywords. I tried adding another one to filter deprecated packages `<RefinementList attributeName="deprecated" defaultRefinement={[false]} />`

This caused this error: `Warning: Failed prop type: Invalid prop `defaultRefinement[0]` supplied to "AlgoliaRefinementList(Translatable(RefinementList))"`

I tried putting `false` in quotes but then no packages were returned.

I'm using react-instantsearch@4

**Comment by vvo** [comment]
cc @samouss

**Comment by Haroenv** [comment]
This is probably because we didn’t set that up for faceting. Let’s add this, it’s a good idea

**Comment by Haroenv** [comment]
What you should be able to do is this (in React InstantSearch): `<Toggle attributeName="deprecated" defaultRefinement={false} />` after I merge #160

**Comment by Haroenv** [comment]
It's now set up for faceting, let me know if you have any other problems @KyleAMathews 👍

**Comment by samouss** [comment]
Thanks @Haroenv!
