### ISSUE TITLE
encoding issues

### ISSUE THREAD

**Issue by Haroenv** [algolia/npm-search#17]
At some point the description is parsed as something else than utf-8. 

this will make emoji show up as something other than their actual code. 

example of that error happening at [floating.js](https://yarnpkg.com/search?q=floating.%20&p=0&is_v=1)

**Comment by vvo** [comment]
Indeed inside the data it's already badly encoded, so it's an issue in the current indexer

**Comment by Haroenv** [comment]
A description that has html escape codes like `&gt;` will also show them escaped once too much (e.g. [emoji-images](https://yarnpkg.com/search/?q=emoji-images&p=0&is_v=1))

**Comment by vvo** [comment]
I think this is necessary, npm is not doing it but I don't think that's right:

![image](https://cloud.githubusercontent.com/assets/123822/22647468/edf5464e-ec71-11e6-8722-d527040d49b7.png)

(from https://www.npmjs.com/package/emoji-images)

**Comment by Haroenv** [comment]
Yep saw that npm is quite wrong on that, but wouldn't a better solution be one that showed it as &lt;img&gt;?

**Comment by vvo** [comment]
That would be nicer yes, we have seen packages with weird content in it that would display it better this way yes, like yarn:

![image](https://cloud.githubusercontent.com/assets/123822/22647525/46679124-ec72-11e6-9b5e-e447de35238a.png)

**Comment by vvo** [comment]
I don't know if those two things have the same root cause, I would say it's different, one is bad encoding the other is "bad" escaping (dumb one)

**Comment by Haroenv** [comment]
close in favour of internal issue
