### ISSUE TITLE
npm description is often less reliable than GitHub description

### ISSUE THREAD

**Issue by Haroenv** [algolia/npm-search#18]
Because the description on npm can basically be full markdown/html, you can do a lot that you can't do in the text field on GitHub. 

IMO it might be an idea to check if a GitHub description is available to use before using the one from npm. 

Yarn for example has 

```
  description: '<p align="center">   <a href="https://yarnpkg.com/">     <img alt="Yarn" src="https://github.com/yarnpkg/assets/blob/master/yarn-kitten-full.png?raw=true" width="546">   </a> </p>',
```

But a GitHub description of

> 📦🐈 Fast, reliable, and secure dependency management. 

This will coincidentally still have the emoji issues described in #17 (but those are internal to the highlighting), but at least it's always *only* text

**Comment by vvo** [comment]
As for this, there's no easy way to solve it but incentive package owners to provide good descriptions (like doing a PR on the yarn package manager).
