### ISSUE TITLE
Download based popular count is not well computed

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#19]
Some libraries are popular while they should not.

```
yarn global add json
curl 'https://ofcncog2cu-dsn.algolia.net/1/indexes/npm-search/jquery?x-algolia-application-id=OFCNCOG2CU&x-algolia-api-key=f54e21fa3a2a0160595bb058179bfb1e' | json popular
true # jQuery is popular inside index
curl http://api.npmjs.org/downloads/point/last-month/jquery | json downloads
2575423 # number of downloads for jQuery last 30 days
curl http://api.npmjs.org/downloads/point/last-month | json downloads
7009616298 # total number of downloads for npm registry last 30 days
```

Popular ratio is 0.005: https://github.com/algolia/npm-search/blob/da6883f174baf6cf3f668bccf3e579e95d3d82da/config.js#L4

Number of downloads for jQuery in one month: 2575423
Number of downloads on the npm registry: 7009616298

Ratio for jQuery: 2575423/7009616298 ~= 0.0003 < 0.005 but still marked as popular

Two issues:
- bad computation of the popular flag
- if computation was right, jQuery won't be popular, we may need to find other ways to say if it's popular or not (but might hit GitHub rate limit again)

**Comment by Haroenv** [comment]
Interestingly `jquery` is showing as popular with 2.6M downloads in the last month, while `jQuery` shows as having 0 downloads. On the npm site they show as having the same number of downloads interestingly. 

* https://www.npmjs.com/package/jQuery
* https://www.npmjs.com/package/jquery

**Comment by vvo** [comment]
Both packages are different sadly which means npm is not doing "the right thing" here.

https://github.com/npm/registry/issues/38

**Comment by Haroenv** [comment]
I think it actually *is* correct, because the ratio is actually multiplied by 100

```js
const downloadsLast30Days = downloadsPerPkgName[pkg.name].downloads;
const downloadsRatio = downloadsLast30Days / totalNpmDownloads * 100;
const popular = downloadsRatio > c.popularDownloadsRatio;
```

`downloadsRatio` is the same as `(downloadsLast30Days / totalNpmDownloads) * 100`.

Applied to (current) data for jquery, this is correct.

```js
jquery = {
  treshold: 0.005,
  totalDownloads: 7282835554,
  downloadsLast30Days: 2693832,
  downloadsRatio() {
    return this.downloadsLast30Days / this.totalDownloads * 100; //0.03698877971397348
  },
  popular() {
    return this.downloadsRatio() > this.treshold; //true
  },
}
```
