### ISSUE TITLE
Automatically restart replication every week

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#20]
To get a downloads data that is always up to date, we need to restart the replication from seq=0 every month.

There should be ways on heroku to do that.

**Comment by Haroenv** [comment]
interesting, scheduler.heroku.com doesn't allow intervals of under a day, which is kind of weird. Maybe the feature is hidden. 

![screen shot 2017-02-07 at 15 49 07](https://cloud.githubusercontent.com/assets/6270048/22696087/27a85620-ed4d-11e6-8f4d-97236bf2a0c6.png)

**Comment by vvo** [comment]
Nice!
