### ISSUE TITLE
Idea: drop `.js` endings to provide better relevancy

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#217]
When searching for "places" we do not find places.js while it's way more popular than `places`
![image](https://user-images.githubusercontent.com/123822/40909526-0fa21d54-67ea-11e8-944e-82ee5f7fceac.png)

![image](https://user-images.githubusercontent.com/123822/40909530-161c53e8-67ea-11e8-9cd5-c62e0dc650e2.png)

**Comment by Haroenv** [comment]
Should put it in alternariveNames indeed, there’s a few packages that are more popular with the .js ending
