### ISSUE TITLE
add GitHub branch

### ISSUE THREAD

**Issue by Haroenv** [algolia/npm-search#22]
some repositories don't store their package on `master`, which causes the location of the README etc to be wrong.

**Comment by redox** [comment]
But the README is also part of the metadata the NPM registry has, isn't it?

**Comment by Haroenv** [comment]
Yes, the README is only one aspect, another is being able to link to the correct branch of a project (think instanstsearch.js (develop) vs react-instantsearch (v2))

**Comment by Haroenv** [comment]
The shasum (gitHead) in npm will be better
