### ISSUE TITLE
Index settings disappeared after full bootstrap

### ISSUE THREAD

**Issue by MartinKolarik** [algolia/npm-search#233]
For some reason when searching for "monaco-editor" the first result is "monaco-editor-x" and "monaco-editor" isn't even in the top ten.

![image](https://user-images.githubusercontent.com/6192491/41969916-4a153ecc-7a09-11e8-8b82-aaeb63c563ed.png)

![image](https://user-images.githubusercontent.com/6192491/41969932-555b11f8-7a09-11e8-9d4c-fdfb59533490.png)

**Comment by Haroenv** [comment]
hmm, seems odd, thanks for reporting!

**Comment by Haroenv** [comment]
Seems like the settings have been lost somehow, this is very odd @vvo

**Comment by Akryum** [comment]
Maybe related:
#69 
https://github.com/vuejs/vue-cli/issues/1897

**Comment by Akryum** [comment]
Looks like https://github.com/algolia/npm-search/issues/235 happened again! 😸
cc @Haroenv

**Comment by Haroenv** [comment]
Ugh! Thanks for notifying me! It didn’t happen last week but it did now. Adding them back ASAP

**Comment by vvo** [comment]
This issue can be dig by looking at the npm-search index inside Algolia more closely with the search api team

**Comment by Haroenv** [comment]
Problem should have happened around midnight CEST yesterday

**Comment by Haroenv** [comment]
This hasn't happened in a really long time, so I think this fixed itself.
