### ISSUE TITLE
Script is not resilient to "db crash"

### ISSUE THREAD

**Issue by bodinsamuel** [algolia/npm-search#382]
Aug 06 13:07:43 npm-search app/worker.1: [unknown_error: Database encountered an unknown error] { 
Aug 06 13:07:43 npm-search app/worker.1:   status: 503, 
Aug 06 13:07:43 npm-search app/worker.1:   name: 'unknown_error', 
Aug 06 13:07:43 npm-search app/worker.1:   message: 'Database encountered an unknown error', 
Aug 06 13:07:43 npm-search app/worker.1:   error: true, 
Aug 06 13:07:43 npm-search app/worker.1:   data: '<html><body>503 Service Unavailable\n' + 
Aug 06 13:07:43 npm-search app/worker.1:     'No server is available to handle this request.\n' + 
Aug 06 13:07:43 npm-search app/worker.1:     '</body></html>\n' + 
Aug 06 13:07:43 npm-search app/worker.1:     '\n' 
Aug 06 13:07:43 npm-search app/worker.1: } 
Aug 06 13:07:43 npm-search app/worker.1: error Command failed with exit code 1.

**Comment by Haroenv** [comment]
This is something I'm aware of, and don't really have a good solution for in mind. instead of crashing and relying on Heroku to be slow enough, we could back off for e.g. 1 minute & back off more exponentially? I didn't add any code since it seemed to be rare that we didn't wait long enough when crashing

**Comment by bodinsamuel** [comment]
We need to check the error handling with PouchDB, a back off would be good enough I believe as it seems to happen very rarely.

**Comment by Haroenv** [comment]
there's a "retry" option, but we should see if it isn't too aggressive https://pouchdb.com/api.html#options-4

**Comment by bodinsamuel** [comment]
Should not happen again
