### ISSUE TITLE
Does GitHub API V4 have any consequences?

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#50]
https://developer.github.com/v4/

Is there any benefit in switching to the new schema? I don't know :)

**Comment by Haroenv** [comment]
We don't really use the GitHub api because of rare limits. Did that get changed?

**Comment by vvo** [comment]
Yep was lost here :)

**Comment by Haroenv** [comment]
Could have impact frontend though, I tried to get the stargazers + commit_activity + some other basic details, but commit_activity isn’t given back AFAIK
