### ISSUE TITLE
Completely reindex weekly

### ISSUE THREAD

**Issue by Haroenv** [algolia/npm-search#51]
packages like [eslint-config-algolia-cdn](https://yarnpkg.com/en/package/eslint-config-algolia-cdn) are actually spam, and removed by `npm` a while ago, so we shouldn't list them either. 

Maybe we should periodically make a second index, fill it from scratch, and then `moveIndex` to replace the main one?

**Comment by Haroenv** [comment]
Maybe it's also possible to check the `unpublished` flag on packages and avoid these, but then they're still not removed. We could send a `deleteObject` for those maybe? 

[registry](https://registry.npmjs.com/eslint-config-algolia-cdn)

**Comment by rally25rs** [comment]
I'm not sure what the infrastructure is behind the scenes, but is it possible that if someone hits the "registry.yarnpkg.org" site and we get back a "deleted" response from NPM, we also remove that entry from the Algolia index?

**Comment by Haroenv** [comment]
Interesting idea, but I fear that might be making it too complicated. I think that by doing something in one of these lines: 

https://github.com/algolia/npm-search/blob/8dd2cdac2e03cc0e4e9b6cc700cdd1519116a894/saveDocs.js#L8-L11

that calls `algoliaIndex.deleteObjects` for the ones that need to be deleted might work. To be sure how that works we’d need to see how the deleted objects are represented in `db.allDocs` as we request here

https://github.com/algolia/npm-search/blob/8dd2cdac2e03cc0e4e9b6cc700cdd1519116a894/index.js#L97-L98

Another option is to have a completely separate process, which periodically `browse`s the complete index, queries the registry to see if it’s deleted, and then applies that deletion to our index. 

If you want to help with this logic, please get in touch and we can raise limits to your Algolia index if the free plan would be used up by the testing

**Comment by Haroenv** [comment]
Just got an update from npm, deleted packages should still be in `allDocs`, so we should take that from there

https://github.com/npm/registry/issues/203#issuecomment-324959811

**Comment by Haroenv** [comment]
fixed in #125
