### ISSUE TITLE
Detect packages with TypeScript but without a `types` field in package.json

### ISSUE THREAD

**Issue by sindresorhus** [algolia/npm-search#511]
Would be nice if the search would correctly detect a package as TypeScript in the case where a package has a `index.d.ts` file in root, but not a `types` field in `package.json`. That's a common occurrence and it's allowed by TypeScript to omit the `types` field if the definition file uses the name `index.d.ts`.

Context: https://github.com/algolia/npm-search/pull/407#issuecomment-584338683

**Comment by Haroenv** [comment]
Do you have an example package that doesn’t get detected yet? That’ll make implementing this easier :)

**Comment by sindresorhus** [comment]
It was https://github.com/sindresorhus/type-fest, but now we've added a types field to work around it: https://github.com/sindresorhus/type-fest/commit/1fe98c2854ea40f5a5d07ec965c6164de11d23fb

**Comment by Haroenv** [comment]
I think the code might have been assuming a `main` field, which is why it doesn't work yet
