### ISSUE TITLE
Add back scoped packages downloads

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#61]

**Comment by Haroenv** [comment]
We could get all the scoped packages when iterating, and then after we downloaded the other ones in batches, get the scoped downloads

**Comment by vvo** [comment]
Sorry thought I had alreayd provided a solution. The fix to this is when we have 200 packages (mix of scoped and not scoped), we should sort them this way:

```js
['@scoped/test', '@scoped/yolo', ['noscoped', 'notscoped2']]; 
// or
{
  scoped: ...,
  unscoped: ...
}
```

Then in the download code, make single requests (but in parallel) and multiple requests for unscoped.

Good?

**Comment by Haroenv** [comment]
Second option seems cleaner IMO

**Comment by vvo** [comment]
Ok, what I want to avoid is slowing down the indexing, since it's totally OK to do lot of requests in parallel
