### ISSUE TITLE
 GitHub stargazers false

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#62]
![image](https://user-images.githubusercontent.com/123822/29777067-06e80450-8c0b-11e7-85b2-3151e397f402.png)

**Comment by vvo** [comment]
https://yarnpkg.com/en/package/react-condition

**Comment by Haroenv** [comment]
This should be moved to the detail page, stargazers are fetched frontend, not in the Algolia index. It's `false` because the github repo doesn't exist. 

closing in favour of https://github.com/yarnpkg/website/issues/621
