### ISSUE TITLE
Reindex to add moduleTypes for all packages

### ISSUE THREAD

**Issue by MartinKolarik** [algolia/npm-search#634]
There are packages that didn't have a new release since the field `moduleTypes` was added and therefore don't have that field in the index. We talked with @Haroenv about doing a full reindex to fix this but there were some issues with the bootstrap process back then.

I got back to this recently and noticed the issue is still there so it'd be great if the full reindex could be done if/when it works.

**Comment by Haroenv** [comment]
cc @bodinsamuel, do you see some method to move the reindex that you're busy doing to the live one to solve this issue?

**Comment by bodinsamuel** [comment]
Still asserting that full reindex is okay, could have done in the correct app from the start that would have saved us 10days 💀 
After the TS migration, I think optimisation will be easier but for now I'm not too confident in touching the codebase.

**Comment by bodinsamuel** [comment]
It's done and we are working on improving packages refresh even without npm updates 👌🏻
