### ISSUE TITLE
some READMEs are the localised (README.cn.md) version instead of the normal one. 

### ISSUE THREAD

**Issue by Haroenv** [algolia/npm-search#67]
reported in https://github.com/yarnpkg/website/issues/711

The README that we have here is in fact the Chinese one: https://ofcncog2cu-dsn.algolia.net/1/indexes/npm-search/postcss?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.24.5&x-algolia-application-id=OFCNCOG2CU&x-algolia-api-key=f54e21fa3a2a0160595bb058179bfb1e

The readme in npm is also the Chinese one: http://registry.npmjs.org/postcss, but their website somehow shows the English version: https://www.npmjs.com/package/postcss

language | link
---|---
cn | <https://yarn.pm/postcss>
cn | <https://ofcncog2cu-dsn.algolia.net/1/indexes/npm-search/postcss?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.24.5&x-algolia-application-id=OFCNCOG2CU&x-algolia-api-key=f54e21fa3a2a0160595bb058179bfb1e>
cn | <https://replicate.npmjs.com/registry/postcss>
cn | <http://registry.npmjs.org/postcss>
en | <https://www.npmjs.com/package/postcss>

cc @ai

**Comment by iarna** [comment]
The npm website pulls version specific readmes from the the tarballs. The readme in the registry is only updated when someone publishes to the `latest` tag. If folks are publishing to another tag (like, say, `next`, the way npm does) and then using `npm dist-tag` to mark it as latest later then the registry readme will never be updated again.

As such, you really have to look in the tarball for the canonical readme for a particular version.

**Comment by redox** [comment]
> The npm website pulls version specific readmes from the the tarballs. The readme in the registry is only updated when someone publishes to the latest tag. If folks are publishing to another tag (like, say, next, the way npm does) and then using npm dist-tag to mark it as latest later then the registry readme will never be updated again.
> 
> As such, you really have to look in the tarball for the canonical readme for a particular version.

That's good to know, thanks for chiming in @iarna !

**Comment by ai** [comment]
Hi. I am maintainer of this package. Latest tag contains two README. With `.md` and `.cn.md` ext. Are you sure that it is not file extension detection problem?

**Comment by Haroenv** [comment]
Not sure we can do anything actionable here, issue seems to be resolved since, but it's completely on npm's API side of things :)
