### ISSUE TITLE
exact package name is not always first result

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#69]
Example: https://yarnpkg.com/en/packages?q=react-native&p=1

![image](https://user-images.githubusercontent.com/123822/32541099-eb249e6c-c46e-11e7-8e92-3c87b181ced8.png)

**Comment by Akryum** [comment]
This is even more visible for `vue-i18n` which appears on the 5th results page.

https://github.com/vuejs/vue-cli/issues/1897

**Comment by Haroenv** [comment]
This is actually already fixed since the new query rules. Reason it wasn’t working for a bit was because of loss of settings
