### ISSUE TITLE
"react native" does not match react-native first

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#70]
https://yarnpkg.com/en/packages?q=react%20native&p=1

![image](https://user-images.githubusercontent.com/123822/32541161-19fd3910-c46f-11e7-8e6c-df4b170bb355.png)

**Comment by Haroenv** [comment]
![54b0d6aa-675e-4134-9fbb-51a1d67ca5a3](https://user-images.githubusercontent.com/6270048/39395900-1137aaa2-4ae5-11e8-8043-0e725fa942ef.png)

It’s different now, but still second.

**Comment by Haroenv** [comment]
This was fixed in #195
