### ISSUE TITLE
New NPM package not found on yarnpkg search

### ISSUE THREAD

**Issue by cpetzel** [algolia/npm-search#726]
I published 2 new packages a few days ago that are currently live and searchable on npmjs, but are not searchable/visible on yarnpkg search.

https://www.npmjs.com/package/flipper-plugin-xstate

https://classic.yarnpkg.com/en/packages?q=flipper-plugin-xstate

Is there something I am missing in the publication process?

**Comment by bodinsamuel** [comment]
Hello, 
sorry about that, it's expected for the moment because of NPM database reset.
We expect to be fully up to date in 6-7 days (yes, that's long unfortunately)
Please find more details here #717

**Comment by Haroenv** [comment]
This reindex has finally been finished now, sorry for the delay!
