### ISSUE TITLE
Valid package missing from the index

### ISSUE THREAD

**Issue by MartinKolarik** [algolia/npm-search#778]
[validated-changeset](https://www.npmjs.com/package/validated-changeset) seems to be [completely missing from the index](https://www.jsdelivr.com/package/npm/validated-changeset) (see failed requests) despite existing for quite a while and not being deprecated 🤔

**Comment by bodinsamuel** [comment]
NB: I did not know the Algolia was in the critical path of jsdelivr, maybe we should produce a different index without 3rd party enrichment to avoid disruption.

**Comment by MartinKolarik** [comment]
It doesn't affect our CDN but affects the website since that relies mostly on the data from the index to render the package pages (I think similarly to https://yarnpkg.com/). A retry strategy would definitely be good.

> maybe we should produce a different index without 3rd party enrichment to avoid disruption.

So it was something else than npm that failed?

**Comment by bodinsamuel** [comment]
> So it was something else than npm that failed?

In that case no, NPM was the issue. But 3rd party is what make the indexing slow, you can have many hours of lag because of this. I don't know if it's acceptable for you, considering that without 3rd party the page would probably empty. 

We can eventually think of "on-demand" endpoint, that you can reach to request a package that seems to 404. But I guess you got a lot of 404 that would also spam us. wdyt?

**Comment by MartinKolarik** [comment]
Right now, we're only using the following attributes, which I think all come from npm?

```
[ 'deprecated', 'description', 'githubRepo', 'homepage', 'keywords', 'license', 'name', 'owner', 'version' ]
```

But that's going to change in a redesign that we're working on right now as we also want to show part of READMEs.

We also query our own API which could be used to prevent 404 calls if there was an on-demand endpoint in the future, but the thing is, most people get to the package pages from the search results. If the search doesn't return the package, the on-demand approach won't help. So it would have to be a combination of npm-only index + the endpoint.

I think a good enough start here is ensuring that we don't miss any packages completely because of temporary errors.

**Comment by Haroenv** [comment]
It's not ideal, but a temporary workaround would be in your frontend to fall back to https://registry.npmjs.com/validated-changeset, as that's a more "pure" source of truth

**Comment by MartinKolarik** [comment]
> It's not ideal, but a temporary workaround would be in your frontend to fall back to https://registry.npmjs.com/validated-changeset, as that's a more "pure" source of truth

Indeed for direct access to that page, we could.

**Comment by bodinsamuel** [comment]
Made a quick and dirty retry strategy @MartinKolarik
