### ISSUE TITLE
Have a deploy preview index

### ISSUE THREAD

**Issue by Haroenv** [algolia/npm-search#79]
Index part of the data, stop at some point (100k records should be enough to have a few interesting packages). Show a version of the website at that point. 

Requires us to have a second heroku worker, since this will take too long to do on Travis. _maybe_ it might be doable with Circle since it's faster, but I'm not sure

**Comment by vvo** [comment]
What is our goal here?

**Comment by Haroenv** [comment]
Be sure things work without needing complicated integration tests
