### ISSUE TITLE
Add browser size information on yarn results

### ISSUE THREAD

**Issue by vvo** [algolia/npm-search#91]
Hi @pastelsky, we are looking at adding browser size information to package on the yarn website.

We were thinking to add information from https://bundlephobia.com/result?p=lodash-es@4.17.4. What do you think? We could implement it an asynchronous request on the details page here: https://yarnpkg.com/en/package/yarn

Let us know what you think!

**Comment by pastelsky** [comment]
Hi @vvo, first of all, that sounds great. However, do note that bundling requests can take very long (>30s) for large uncached packages.
Also I'd be interested in knowing the traffic I should expect to receive if such an arrangement was made.

**Comment by Haroenv** [comment]
If we are doing it frontend: 10k visits per day on the whole site. Can’t see a way to extract page detail visits in google analytics

**Comment by vvo** [comment]
@pastelsky It's 1K package views per day nowadays. So it means we would call your API between 1K and 2K times per day.

If that's doable, how can we move forward? Thanks!

**Comment by pastelsky** [comment]
Sounds good. I'm planning to move to a different hosting solution soon, so 1k requests shouldn't be a major issue. Let me know what's required from my side for this. Do you think it would be helpful if we link the size stats back to the details page on bundlephobia ? Also, it would be great if the requests have a `X` header that can help me identify the source for these requests.

**Comment by vvo** [comment]
> Do you think it would be helpful if we link the size stat on yarn back to the details page on bundlephobia ?

Yes totally doable if your page has more details, and just for the sake of giving back to the source of the data.

> Also, it would be great if the requests have a X header that can help me identify the source for these requests.

Again, totally doable.

> Let me know what's required from my side for this

Give us an API endpoint that we can call and the associated parameters.

**Comment by pastelsky** [comment]
The API endpoint would be - `https://bundlephobia.com/api/size?package=<package-name>@<package-version>`.

These work fine -
https://bundlephobia.com/api/size?package=react 
https://bundlephobia.com/api/size?package=react@15.3.0

**Comment by Haroenv** [comment]
Should we do it backend too? I fear the fetching will take too long though, maybe there's some cache we can replicate?

**Comment by vvo** [comment]
@pastelsky You should add some browser cache like one hour for non specific versions (bundlephobia.com/api/size?package=react) and unlimited cache for specific versions (bundlephobia.com/api/size?package=react@15.3.0)

Doing so you could then have a CDN on top of that, there are some that would maybe be happy sponsoring your service (cloudflare?). So that any request from Yarn on specific versions would be cached forever in Cloudflare.
